name: autocommit-robot

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v1

      - name: "Set node"
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: "Install"
        run: npm install

      - name: "Decide to run"
        id: decide
        run: echo "RANDOM_NUMBER=$((RANDOM % 3))" >> $GITHUB_ENV

      - name: "Run bash"
        if: env.RANDOM_NUMBER != '0'
        run: node index.js

      - name: "Commit"
        if: env.RANDOM_NUMBER != '0'
        uses: EndBug/add-and-commit@v4
        with:
          author_name: mongorolls
          author_email: xuzhichao1618@qq.com
          message: "feat: save robot"
          add: "pictures/*"

        env:
          GITHUB_TOKEN: ${{ secrets.MONGO }}