name: autocommit-robot

on:
  schedule:
    - cron: "0 0 */9 * *" # 每天0点执行,注意时区要+8
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  bots:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 明确给予写入内容的权限
    steps:
    # 代码检出
      - name: "Checkout code"
        uses: actions/checkout@v3  
    # 设置Node.js环境
      - name: "Set node"
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: "Install"
        run: npm install

      - name: "Run bash"
        run: node index.js
        env:
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
     
      # 提交github更改
      - name: "Commit"
        uses: EndBug/add-and-commit@v9  # 更新到v9
        with:
          author_name: mongorolls
          author_email: 1467513807@qq.com
          message: "feat: save landscape photo"
          add: "pictures/*"
        env:
          GITHUB_TOKEN: ${{ secrets.MONGO }}